language: csharp
mono:
  - latest
solution: StringTemplate.sln
install:
  - sudo apt-get install -y gtk-sharp2
  - nuget restore StringTemplate.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release StringTemplate.sln
  - mono ./testrunner/xunit.runners.*/tools/xunit.console.clr4.exe ./StringTemplate.Tests/bin/Release/StringTemplate.Tests.dll
after_success:
  - cp -f ./StringTemplate/bin/Release/StringTemplate.dll ./bin/StringTemplate.dll


