language: csharp
mono:
  - latest
solution: StringTemplate.sln
install:
  - sudo apt-get install -y gtk-sharp2
  - nuget restore StringTemplate.sln
  - nuget install xunit.runners -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release StringTemplate.sln
  - mono ./packages/xunit.runner.console.*/tools/xunit.console.exe ./StringTemplate.Tests/bin/Release/StringTemplate.Tests.dll


